version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node16.5.0-chrome94-ff93'
workflows:
  build:
    jobs:
      - cypress/run:
          name: update npm
          command: "npm run test-junit"
          executor: with-chrome
          post-steps:
            - store_test_results:
                path: junit-results
            - store_artifacts:
                path: cypress/screenshots
            - store_artifacts:
                path: cypress/videos