version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: update npm
          command: "npx cypress run"
          post-steps:
            - store_test_results:
                path: mochawesome-report
            - store_artifacts:
                path: cypress/screenshots
            - store_artifacts:
                path: cypress/videos